# Generated by Django 2.1.5 on 2019-07-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190706_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'ordering': ['user', 'bio']},
        ),
    ]
